//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localizator.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localizator.Shared.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured..
        /// </summary>
        public static string AnErrorOccured {
            get {
                return ResourceManager.GetString("AnErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one language must be supported.
        /// </summary>
        public static string AtLeastOneLanguageRequired {
            get {
                return ResourceManager.GetString("AtLeastOneLanguageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization header not found.
        /// </summary>
        public static string AuthorizationHeaderNotFound {
            get {
                return ResourceManager.GetString("AuthorizationHeaderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad gateway error occurred..
        /// </summary>
        public static string BadGateway {
            get {
                return ResourceManager.GetString("BadGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base64 conversion error.
        /// </summary>
        public static string Base64ConversionError {
            get {
                return ResourceManager.GetString("Base64ConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization header doesn&apos;t start with Basic.
        /// </summary>
        public static string BasicAuthorizationHeaderInvalidFormat {
            get {
                return ResourceManager.GetString("BasicAuthorizationHeaderInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Credentials don&apos;t match.
        /// </summary>
        public static string BasicCredentialsDontMatch {
            get {
                return ResourceManager.GetString("BasicCredentialsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearer token missing..
        /// </summary>
        public static string BearerTokenMissing {
            get {
                return ResourceManager.GetString("BearerTokenMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change slug of published or archived namespace.
        /// </summary>
        public static string CannotChangePublishedSlug {
            get {
                return ResourceManager.GetString("CannotChangePublishedSlug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot modify archived namespace.
        /// </summary>
        public static string CannotModifyArchivedNamespace {
            get {
                return ResourceManager.GetString("CannotModifyArchivedNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot publish archived namespace.
        /// </summary>
        public static string CannotPublishArchivedNamespace {
            get {
                return ResourceManager.GetString("CannotPublishArchivedNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot unpublish archived namespace.
        /// </summary>
        public static string CannotUnpublishArchivedNamespace {
            get {
                return ResourceManager.GetString("CannotUnpublishArchivedNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update name of archived namespace.
        /// </summary>
        public static string CannotUpdateArchivedNamespace {
            get {
                return ResourceManager.GetString("CannotUpdateArchivedNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to context.Resource is not Microsoft.AspNetCore.Http.HttpContext.
        /// </summary>
        public static string ContextResourceIsNotHttpContext {
            get {
                return ResourceManager.GetString("ContextResourceIsNotHttpContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create development user: {0}.
        /// </summary>
        public static string FailedToCreateDevUser {
            get {
                return ResourceManager.GetString("FailedToCreateDevUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create identity user: {0}.
        /// </summary>
        public static string FailedToCreateIdentityUser {
            get {
                return ResourceManager.GetString("FailedToCreateIdentityUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access this resource..
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler method not found for {0}.
        /// </summary>
        public static string HandlerMethodNotFound {
            get {
                return ResourceManager.GetString("HandlerMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal server error occurred..
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid authorization scheme..
        /// </summary>
        public static string InvalidAuthorizationScheme {
            get {
                return ResourceManager.GetString("InvalidAuthorizationScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credential format.
        /// </summary>
        public static string InvalidCredentialFormat {
            get {
                return ResourceManager.GetString("InvalidCredentialFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All language codes must be 2-letter ISO codes.
        /// </summary>
        public static string InvalidLanguageCode {
            get {
                return ResourceManager.GetString("InvalidLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid namespace permission..
        /// </summary>
        public static string InvalidNamespacePermission {
            get {
                return ResourceManager.GetString("InvalidNamespacePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OIDC token validation failed..
        /// </summary>
        public static string InvalidOIDCToken {
            get {
                return ResourceManager.GetString("InvalidOIDCToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or missing API Key.
        /// </summary>
        public static string InvalidOrMissingAPIKey {
            get {
                return ResourceManager.GetString("InvalidOrMissingAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is invalid..
        /// </summary>
        public static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid version bump type.
        /// </summary>
        public static string InvalidVersionBumpType {
            get {
                return ResourceManager.GetString("InvalidVersionBumpType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameIdentifier claim missing.
        /// </summary>
        public static string NameIdentifierClaimMissing {
            get {
                return ResourceManager.GetString("NameIdentifierClaimMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace is already archived.
        /// </summary>
        public static string NamespaceAlreadyArchived {
            get {
                return ResourceManager.GetString("NamespaceAlreadyArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace is already in draft status.
        /// </summary>
        public static string NamespaceAlreadyDraft {
            get {
                return ResourceManager.GetString("NamespaceAlreadyDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace is already published.
        /// </summary>
        public static string NamespaceAlreadyPublished {
            get {
                return ResourceManager.GetString("NamespaceAlreadyPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NamespaceId cannot be empty.
        /// </summary>
        public static string NamespaceIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("NamespaceIdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace must support at least one language.
        /// </summary>
        public static string NamespaceMustSupportOneLanguage {
            get {
                return ResourceManager.GetString("NamespaceMustSupportOneLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace name cannot be empty.
        /// </summary>
        public static string NamespaceNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("NamespaceNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace name cannot exceed 100 characters.
        /// </summary>
        public static string NamespaceNameTooLong {
            get {
                return ResourceManager.GetString("NamespaceNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace permission cannot be null..
        /// </summary>
        public static string NamespacePermissionCannotBeNull {
            get {
                return ResourceManager.GetString("NamespacePermissionCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace slug cannot be empty.
        /// </summary>
        public static string NamespaceSlugCannotBeEmpty {
            get {
                return ResourceManager.GetString("NamespaceSlugCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace slug can only contain lowercase letters, numbers and hyphens.
        /// </summary>
        public static string NamespaceSlugInvalidFormat {
            get {
                return ResourceManager.GetString("NamespaceSlugInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace slug cannot exceed 50 characters.
        /// </summary>
        public static string NamespaceSlugTooLong {
            get {
                return ResourceManager.GetString("NamespaceSlugTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status cannot be empty.
        /// </summary>
        public static string NamespaceStatusCannotBeEmpty {
            get {
                return ResourceManager.GetString("NamespaceStatusCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid status. Must be one of: {0}.
        /// </summary>
        public static string NamespaceStatusInvalid {
            get {
                return ResourceManager.GetString("NamespaceStatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version cannot be empty.
        /// </summary>
        public static string NamespaceVersionCannotBeEmpty {
            get {
                return ResourceManager.GetString("NamespaceVersionCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version must follow semantic versioning (e.g., 1.0.0).
        /// </summary>
        public static string NamespaceVersionInvalidFormat {
            get {
                return ResourceManager.GetString("NamespaceVersionInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality is not implemented..
        /// </summary>
        public static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only archived namespaces can be restored.
        /// </summary>
        public static string OnlyArchivedCanBeRestored {
            get {
                return ResourceManager.GetString("OnlyArchivedCanBeRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published date cannot be in the future.
        /// </summary>
        public static string PublishedDateCannotBeFuture {
            get {
                return ResourceManager.GetString("PublishedDateCannotBeFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher identifier cannot be empty.
        /// </summary>
        public static string PublisherIdentifierCannotBeEmpty {
            get {
                return ResourceManager.GetString("PublisherIdentifierCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request was cancelled by the client..
        /// </summary>
        public static string RequestCancelled {
            get {
                return ResourceManager.GetString("RequestCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request timed out..
        /// </summary>
        public static string RequestTimeout {
            get {
                return ResourceManager.GetString("RequestTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found in environment ({0}).
        /// </summary>
        public static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to perform this action..
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User identifier missing.
        /// </summary>
        public static string UserIdentifierMissing {
            get {
                return ResourceManager.GetString("UserIdentifierMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more validation errors occurred..
        /// </summary>
        public static string ValidationFailed {
            get {
                return ResourceManager.GetString("ValidationFailed", resourceCulture);
            }
        }
    }
}
