// <auto-generated />
using System;
using Localizator.Namespace.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Localizator.Namespace.Infrastructure.Localizator.Namespace.Localizator.Namespace.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NamespaceDbContext))]
    partial class NamespaceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Localizator.Namespace.Domain.Namespace.Namespace", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsPublic");

                    b.ToTable("Namespaces", (string)null);
                });

            modelBuilder.Entity("Localizator.Namespace.Domain.Namespace.Namespace", b =>
                {
                    b.OwnsOne("Localizator.Namespace.Domain.Namespace.ValueObjects.NamespaceName", "Name", b1 =>
                        {
                            b1.Property<long>("NamespaceId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Name");

                            b1.HasKey("NamespaceId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Namespaces");

                            b1.WithOwner()
                                .HasForeignKey("NamespaceId");
                        });

                    b.OwnsOne("Localizator.Namespace.Domain.Namespace.ValueObjects.NamespaceSlug", "Slug", b1 =>
                        {
                            b1.Property<long>("NamespaceId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Slug");

                            b1.HasKey("NamespaceId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Namespaces");

                            b1.WithOwner()
                                .HasForeignKey("NamespaceId");
                        });

                    b.OwnsOne("Localizator.Namespace.Domain.Namespace.ValueObjects.NamespaceStatus", "Status", b1 =>
                        {
                            b1.Property<long>("NamespaceId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Status");

                            b1.HasKey("NamespaceId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Namespaces");

                            b1.WithOwner()
                                .HasForeignKey("NamespaceId");
                        });

                    b.OwnsMany("Localizator.Namespace.Domain.Namespace.ValueObjects.NamespaceUserPermission", "Permissions", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<long>("NamespaceId")
                                .HasColumnType("bigint");

                            b1.Property<string>("User")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("User");

                            b1.HasKey("Id");

                            b1.HasIndex("NamespaceId", "User")
                                .IsUnique();

                            b1.ToTable("NamespaceUserPermissions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("NamespaceId");

                            b1.OwnsMany("Localizator.Namespace.Domain.Namespace.ValueObjects.NamespacePermission", "Permissions", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("NamespaceUserPermissionId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Permission")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("Permission");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("Id");

                                    b2.HasIndex("NamespaceUserPermissionId", "Permission")
                                        .IsUnique();

                                    b2.ToTable("NamespacePermissions", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("NamespaceUserPermissionId");
                                });

                            b1.Navigation("Permissions");
                        });

                    b.OwnsOne("Localizator.Namespace.Domain.Namespace.ValueObjects.NamespaceVersion", "CurrentVersion", b1 =>
                        {
                            b1.Property<long>("NamespaceId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("CurrentVersion");

                            b1.HasKey("NamespaceId");

                            b1.ToTable("Namespaces");

                            b1.WithOwner()
                                .HasForeignKey("NamespaceId");
                        });

                    b.OwnsOne("Localizator.Namespace.Domain.Namespace.ValueObjects.PublishedAt", "LastPublishedAt", b1 =>
                        {
                            b1.Property<long>("NamespaceId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastPublishedAt");

                            b1.HasKey("NamespaceId");

                            b1.ToTable("Namespaces");

                            b1.WithOwner()
                                .HasForeignKey("NamespaceId");
                        });

                    b.OwnsOne("Localizator.Namespace.Domain.Namespace.ValueObjects.PublishedBy", "LastPublishedBy", b1 =>
                        {
                            b1.Property<long>("NamespaceId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("LastPublishedBy");

                            b1.HasKey("NamespaceId");

                            b1.ToTable("Namespaces");

                            b1.WithOwner()
                                .HasForeignKey("NamespaceId");
                        });

                    b.OwnsMany("Localizator.Namespace.Domain.Namespace.ValueObjects.SupportedLanguage", "SupportedLanguages", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("Id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("LanguageCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("LanguageCode");

                            b1.Property<long>("NamespaceId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("NamespaceId");

                            b1.HasIndex("NamespaceId", "LanguageCode")
                                .IsUnique();

                            b1.ToTable("NamespaceSupportedLanguages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("NamespaceId");
                        });

                    b.Navigation("CurrentVersion")
                        .IsRequired();

                    b.Navigation("LastPublishedAt");

                    b.Navigation("LastPublishedBy");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Permissions");

                    b.Navigation("Slug")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();

                    b.Navigation("SupportedLanguages");
                });
#pragma warning restore 612, 618
        }
    }
}
